//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bram.EnEllerEtt.Adapter.AngleSharp.UnitTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bram.EnEllerEtt.Adapter.AngleSharp.UnitTests.Resources.HtmlStrings", typeof(HtmlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;client-nojs&quot; lang=&quot;sv&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///&lt;title&gt;barn - Wiktionary&lt;/title&gt;
        ///&lt;script&gt;document.documentElement.className=&quot;client-js&quot;;RLCONF={&quot;wgBreakFrames&quot;:!1,&quot;wgSeparatorTransformTable&quot;:[&quot;,\t.&quot;,&quot; \t,&quot;],&quot;wgDigitTransformTable&quot;:[&quot;&quot;,&quot;&quot;],&quot;wgDefaultDateFormat&quot;:&quot;dmy&quot;,&quot;wgMonthNames&quot;:[&quot;&quot;,&quot;januari&quot;,&quot;februari&quot;,&quot;mars&quot;,&quot;april&quot;,&quot;maj&quot;,&quot;juni&quot;,&quot;juli&quot;,&quot;augusti&quot;,&quot;september&quot;,&quot;oktober&quot;,&quot;november&quot;,&quot;december&quot;],&quot;wgRequestId&quot;:&quot;160583df-0eae-406b-a757-c47047368577&quot;,&quot;wgCSPNonce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Barn {
            get {
                return ResourceManager.GetString("Barn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;client-nojs&quot; lang=&quot;sv&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///&lt;title&gt;dryck - Wiktionary&lt;/title&gt;
        ///&lt;script&gt;document.documentElement.className=&quot;client-js&quot;;RLCONF={&quot;wgBreakFrames&quot;:!1,&quot;wgSeparatorTransformTable&quot;:[&quot;,\t.&quot;,&quot; \t,&quot;],&quot;wgDigitTransformTable&quot;:[&quot;&quot;,&quot;&quot;],&quot;wgDefaultDateFormat&quot;:&quot;dmy&quot;,&quot;wgMonthNames&quot;:[&quot;&quot;,&quot;januari&quot;,&quot;februari&quot;,&quot;mars&quot;,&quot;april&quot;,&quot;maj&quot;,&quot;juni&quot;,&quot;juli&quot;,&quot;augusti&quot;,&quot;september&quot;,&quot;oktober&quot;,&quot;november&quot;,&quot;december&quot;],&quot;wgRequestId&quot;:&quot;62fb74ec-8909-4594-9aba-19b30e2f0190&quot;,&quot;wgCSPNonc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dryck {
            get {
                return ResourceManager.GetString("Dryck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;client-nojs&quot; lang=&quot;sv&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///&lt;title&gt;gäspa - Wiktionary&lt;/title&gt;
        ///&lt;script&gt;document.documentElement.className=&quot;client-js&quot;;RLCONF={&quot;wgBreakFrames&quot;:false,&quot;wgSeparatorTransformTable&quot;:[&quot;,\t.&quot;,&quot; \t,&quot;],&quot;wgDigitTransformTable&quot;:[&quot;&quot;,&quot;&quot;],&quot;wgDefaultDateFormat&quot;:&quot;dmy&quot;,&quot;wgMonthNames&quot;:[&quot;&quot;,&quot;januari&quot;,&quot;februari&quot;,&quot;mars&quot;,&quot;april&quot;,&quot;maj&quot;,&quot;juni&quot;,&quot;juli&quot;,&quot;augusti&quot;,&quot;september&quot;,&quot;oktober&quot;,&quot;november&quot;,&quot;december&quot;],&quot;wgRequestId&quot;:&quot;e821990a-2960-4b96-8a8f-c1d9824c6e3a&quot;,&quot;wgCSPN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gäspa {
            get {
                return ResourceManager.GetString("Gäspa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;client-nojs&quot; lang=&quot;sv&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///&lt;title&gt;mat - Wiktionary&lt;/title&gt;
        ///&lt;script&gt;document.documentElement.className=&quot;client-js&quot;;RLCONF={&quot;wgBreakFrames&quot;:!1,&quot;wgSeparatorTransformTable&quot;:[&quot;,\t.&quot;,&quot; \t,&quot;],&quot;wgDigitTransformTable&quot;:[&quot;&quot;,&quot;&quot;],&quot;wgDefaultDateFormat&quot;:&quot;dmy&quot;,&quot;wgMonthNames&quot;:[&quot;&quot;,&quot;januari&quot;,&quot;februari&quot;,&quot;mars&quot;,&quot;april&quot;,&quot;maj&quot;,&quot;juni&quot;,&quot;juli&quot;,&quot;augusti&quot;,&quot;september&quot;,&quot;oktober&quot;,&quot;november&quot;,&quot;december&quot;],&quot;wgRequestId&quot;:&quot;25dc6445-7628-4b3e-9296-06fb680b94f6&quot;,&quot;wgCSPNonce&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mat {
            get {
                return ResourceManager.GetString("Mat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;client-nojs&quot; lang=&quot;sv&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///&lt;title&gt;prata - Wiktionary&lt;/title&gt;
        ///&lt;script&gt;document.documentElement.className=&quot;client-js&quot;;RLCONF={&quot;wgBreakFrames&quot;:false,&quot;wgSeparatorTransformTable&quot;:[&quot;,\t.&quot;,&quot; \t,&quot;],&quot;wgDigitTransformTable&quot;:[&quot;&quot;,&quot;&quot;],&quot;wgDefaultDateFormat&quot;:&quot;dmy&quot;,&quot;wgMonthNames&quot;:[&quot;&quot;,&quot;januari&quot;,&quot;februari&quot;,&quot;mars&quot;,&quot;april&quot;,&quot;maj&quot;,&quot;juni&quot;,&quot;juli&quot;,&quot;augusti&quot;,&quot;september&quot;,&quot;oktober&quot;,&quot;november&quot;,&quot;december&quot;],&quot;wgRequestId&quot;:&quot;56743b98-1ba1-4a00-a003-317b40fa81cd&quot;,&quot;wgCSPN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prata {
            get {
                return ResourceManager.GetString("Prata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html class=&quot;client-nojs&quot; lang=&quot;sv&quot; dir=&quot;ltr&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta charset=&quot;UTF-8&quot;/&gt;
        ///&lt;title&gt;springa - Wiktionary&lt;/title&gt;
        ///&lt;script&gt;document.documentElement.className=&quot;client-js&quot;;RLCONF={&quot;wgBreakFrames&quot;:false,&quot;wgSeparatorTransformTable&quot;:[&quot;,\t.&quot;,&quot; \t,&quot;],&quot;wgDigitTransformTable&quot;:[&quot;&quot;,&quot;&quot;],&quot;wgDefaultDateFormat&quot;:&quot;dmy&quot;,&quot;wgMonthNames&quot;:[&quot;&quot;,&quot;januari&quot;,&quot;februari&quot;,&quot;mars&quot;,&quot;april&quot;,&quot;maj&quot;,&quot;juni&quot;,&quot;juli&quot;,&quot;augusti&quot;,&quot;september&quot;,&quot;oktober&quot;,&quot;november&quot;,&quot;december&quot;],&quot;wgRequestId&quot;:&quot;58f32d0f-f2ff-493f-a989-3ed34dbf17dc&quot;,&quot;wgCS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Springa {
            get {
                return ResourceManager.GetString("Springa", resourceCulture);
            }
        }
    }
}
